app:
  env: local
  port: "8080"
  app_name: ChatRepository
  version: 1
log: 
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backup: 7
mysql: 
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root123456"
  dbname: "chat_db"
  max_open_conns: 200
  max_idle_conns: 50