app:
  env: local
  port: ":8080"
  app_name: ChatRepository
  version: 1
  path: "./data/"
log: 
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backup: 7
mysql: 
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root123456"
  dbname: "chat_db"
  max_open_conns: 200
  max_idle_conns: 50
postgres:
  host: "192.168.31.103"
  port: 5432
  user: "postgres"
  password: "admin123"
  dbname: "chat_db"
  SetMaxOpenConns: 200
  SetMaxIdleConns: 50